import Head from 'next/head'
import { Nav, Landing, Footer } from "../components/index";

export default function Home() {
  return (
    <div className='flex flex-col items-center justify-center h-screen'>
      <Head>
        <title>google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Nav />
    <Landing />
    <Footer />
    </div>
  )
}
